### ISSUE TITLE
PropertyFileReader doesn't handle CR LF line endings

### ISSUE THREAD

**Issue by novoj** [hupfdule/apron#11]
The current implementation of PropertyFileReader does not parse logical lines correctly in case the physical line contains \r\n line ending characters. The backslash is read, the \r is treated as escaped, but then the \n character is read in the next loop interation and is treated as a new line. I modified an existing testcase to show this. I propose the following fix to PropertyFileReader parsing loop.

**Comment by hupfdule** [comment]
The bug can be confirmed. 

Just some clarifications about the nature of the bug.

An entry in a `.properties` file can span several lines if the line termination characters are escaped via backslash. For example:

```
key = value \
  over two lines
```

would be the same as 

```
key = value over two lines
```

The problem is that a line termination character in a `.properties` file can be either `\n` or `\r` or `\r\n`. 
The current implementation requires that _each_ escape sequence must be prepended by a backslash. However for `\r\n` only one backslash is actually enough: `\\r\n`.
